server:
  port: 8080

spring:
  application:
    name: kafka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/kafka?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
  sql:
    init:
      mode: always
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

kafka:
  bootstrap-servers: 127.0.0.1:9092
  group-id: your-group-name
  topic: your-topic
  consumer-id: MultiThreadConsumer
  max-poll-records: 5000

